# Generated by Django 6.1 on 2026-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio ($)')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='repuestos/', verbose_name='Foto del Repuesto')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
            },
        ),
    ]
