# Generated by Django 6.1 on 2026-09-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Servicio')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('costo_mano_obra', models.PositiveIntegerField(verbose_name='Mano de Obra ($)')),
                ('tiempo_minutos', models.PositiveIntegerField(verbose_name='Tiempo Estimado (min)')),
                ('pauta_tecnica', models.FileField(blank=True, null=True, upload_to='pautas_pdf/', verbose_name='Pauta Técnica (PDF)')),
            ],
            options={
                'verbose_name': 'Servicio de Mantenimiento',
                'verbose_name_plural': 'Servicios de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente_moto', models.CharField(max_length=10, verbose_name='Patente')),
                ('modelo_moto', models.CharField(max_length=100, verbose_name='Modelo Moto')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre Cliente')),
                ('kilometraje', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total ($)')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repuestos.repuesto', verbose_name='Repuesto Utilizado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.serviciomantenimiento', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
            },
        ),
    ]
